#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude node_modules \
	. 'europa:~/flixbus-rest/'

ssh europa "\
cd ~/flixbus-rest
npm i
npm update
forever-service delete flixbus-rest
forever-service install flixbus-rest --start -s index.js"
