#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude node_modules \
	. 'enceladus:~/meinfernbus-rest/'

ssh enceladus "\
cd ~/meinfernbus-rest
npm i
npm update
forever stop meinfernbus-rest
forever start -a --uid meinfernbus-rest index.js"
