#!/bin/sh

rsync -rav --delete \
	--exclude '.*' \
	--exclude node_modules \
	. 'meinfernbus:~/meinfernbus-rest/'

ssh meinfernbus "\
cd ~/meinfernbus-rest
npm i
npm update
export NODE_ENV=production
forever stop meinfernbus-rest
forever start -a --uid meinfernbus-rest index.js"
